[pytest]
testpaths = tests
addopts =
    --html=reports/report.html
    --self-contained-html
    -v
    -s
    --tb=short
markers =
    signup: 회원가입 관련 테스트
    login: 로그인 관련 테스트
    community: 커뮤니티 관련 테스트
    post: 포스트 CRUD 관련 테스트
